# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://kimbabmoowoo.github.io/
baseurl: /
title: Donghoon Kang
author: Donghoon Kang
description: Personal webpage
avatar: profile.png
github: kimbabmowoo# username

# needed for travis-ci build
exclude: [vendor]
